apiVersion: v1
kind: Pod
metadata:
   name: hbd
   labels:
     name: $img
spec:
   containers:
   - name : nginx
     image: farhanmuhammadnajib/test:latest-HappyBirthdayApp
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hbd-app
spec:
  selector:
    name: hbd
  ports:
    - port: 80
  type: LoadBalancer