apiVersion: v1
kind: Pod
metadata:
   name: nginx
   labels:
     name: nginx
spec:
   containers:
   - name : nginx-$env
     image: $img
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    name: nginx
  ports:
    - port: 80
  type: LoadBalancer