apiVersion: v1
kind: Pod
metadata:
   name: hbd
   labels:
     name: hbd
spec:
   containers:
   - name : nginx
     image: $DOCKERHUB_USERNAME/$Docker_Repo:$Docker_Tags -Latest
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hbd-app
spec:
  selector:
    name: hbd
  ports:
    - port: 80
  type: LoadBalancer