name: Docker Build and Push

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Docker:
    name: Docker Build and Push
    environment: "Prod"
    runs-on: Ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: farhanmuhammadnajib/${{vars.Docker_Repo}}:${{vars.Docker_Tags}}