name: Kubernetes OKE OCI Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # Docker:
  #   name: Docker Build and Push
  #   environment: "Prod"
  #   runs-on: Ubuntu-latest
  #   steps:
  #   - name: Check out the repo
  #     uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0

  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #   - name: Build and push image
  #     uses: docker/build-push-action@v4
  #     with:
  #       context: .
  #       push: true
  #       tags: farhanmuhammadnajib/${{vars.Docker_Repo}}:${{vars.Docker_Tags}}
  DeployOKE:
    runs-on: ubuntu-latest
    name: Deploy with Kubectl for OKE
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.3.1
        id: test-configure-kubectl-oke-action
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}
      - name: Deploy App
        run: kubectl apply -f Kubernetes/Test.yaml
      - name: check pod
        run: kubectl get pods
      - name: Check service
        run: kubectl get service
      